// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: cyclops.proto

package cyclops

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CyclopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	EntityType string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityName string `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Workflow   string `protobuf:"bytes,4,opt,name=workflow,proto3" json:"workflow,omitempty"`
}

func (x *CyclopsRequest) Reset() {
	*x = CyclopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyclops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CyclopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CyclopsRequest) ProtoMessage() {}

func (x *CyclopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyclops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CyclopsRequest.ProtoReflect.Descriptor instead.
func (*CyclopsRequest) Descriptor() ([]byte, []int) {
	return file_cyclops_proto_rawDescGZIP(), []int{0}
}

func (x *CyclopsRequest) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *CyclopsRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CyclopsRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *CyclopsRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

type CyclopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CyclopsResponse) Reset() {
	*x = CyclopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyclops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CyclopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CyclopsResponse) ProtoMessage() {}

func (x *CyclopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyclops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CyclopsResponse.ProtoReflect.Descriptor instead.
func (*CyclopsResponse) Descriptor() ([]byte, []int) {
	return file_cyclops_proto_rawDescGZIP(), []int{1}
}

func (x *CyclopsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CyclopsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cyclops_proto protoreflect.FileDescriptor

var file_cyclops_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8f, 0x01, 0x0a, 0x0e, 0x43, 0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x3a, 0x0a, 0x07, 0x43, 0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x12, 0x2f, 0x0a,
	0x0a, 0x53, 0x79, 0x6e, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0f, 0x2e, 0x43, 0x79,
	0x63, 0x6c, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43,
	0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x38, 0x30, 0x61,
	0x73, 0x69, 0x73, 0x2f, 0x63, 0x79, 0x63, 0x6c, 0x6f, 0x70, 0x73, 0x2f, 0x63, 0x79, 0x63, 0x6c,
	0x6f, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cyclops_proto_rawDescOnce sync.Once
	file_cyclops_proto_rawDescData = file_cyclops_proto_rawDesc
)

func file_cyclops_proto_rawDescGZIP() []byte {
	file_cyclops_proto_rawDescOnce.Do(func() {
		file_cyclops_proto_rawDescData = protoimpl.X.CompressGZIP(file_cyclops_proto_rawDescData)
	})
	return file_cyclops_proto_rawDescData
}

var file_cyclops_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cyclops_proto_goTypes = []interface{}{
	(*CyclopsRequest)(nil),  // 0: CyclopsRequest
	(*CyclopsResponse)(nil), // 1: CyclopsResponse
}
var file_cyclops_proto_depIdxs = []int32{
	0, // 0: Cyclops.SyncEntity:input_type -> CyclopsRequest
	1, // 1: Cyclops.SyncEntity:output_type -> CyclopsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cyclops_proto_init() }
func file_cyclops_proto_init() {
	if File_cyclops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cyclops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CyclopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyclops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CyclopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cyclops_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyclops_proto_goTypes,
		DependencyIndexes: file_cyclops_proto_depIdxs,
		MessageInfos:      file_cyclops_proto_msgTypes,
	}.Build()
	File_cyclops_proto = out.File
	file_cyclops_proto_rawDesc = nil
	file_cyclops_proto_goTypes = nil
	file_cyclops_proto_depIdxs = nil
}
